require:
  - rubocop-performance
  - rubocop-rspec
AllCops:
  TargetRubyVersion: 2.6
  DisplayCopNames: true
  DisplayStyleGuide: true
LineLength:
  Max: 100
Style/ExpandPathArguments:
  Enabled: false
